[package]
authors = ["sven"]
edition = "2018"
name = "suricata-kafka-output"
version = "0.0.2"

[lib]
crate-type = ["cdylib"]
name = "kafka_output"

[dependencies]
rdkafka = "0.25"
suricata = {version = "7.0.0-alpha.5", package = "suricata"}